// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxnbnuazpzzuttdunkta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bmJudWF6cHp6dXR0ZHVua3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1Mzk5MjcsImV4cCI6MjA2ODExNTkyN30.tcPBX_Lfvt2XGLEZIgWNgy7E3RRFNpaAxFbBKMuLZQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});